
package com.rapidclipse.vacationplanner.ui.component;

import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;


public class BeanVoting extends HorizontalLayout
{
	public BeanVoting(final Double ranking)
	{
		super();
		this.initUI();
		
		if(ranking == 1)
		{
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR_O.create());
			this.add(VaadinIcon.STAR_O.create());
			this.add(VaadinIcon.STAR_O.create());
			this.add(VaadinIcon.STAR_O.create());
		}
		else if(ranking == 1.5)
		{
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR_HALF_LEFT.create());
			this.add(VaadinIcon.STAR_O.create());
			this.add(VaadinIcon.STAR_O.create());
			this.add(VaadinIcon.STAR_O.create());
		}
		else if(ranking == 2)
		{
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR_O.create());
			this.add(VaadinIcon.STAR_O.create());
			this.add(VaadinIcon.STAR_O.create());
		}
		else if(ranking == 2.5)
		{
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR_HALF_LEFT.create());
			this.add(VaadinIcon.STAR_O.create());
			this.add(VaadinIcon.STAR_O.create());
		}
		else if(ranking == 3)
		{
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR_O.create());
			this.add(VaadinIcon.STAR_O.create());
		}
		else if(ranking == 3.5)
		{
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR_HALF_LEFT.create());
			this.add(VaadinIcon.STAR_O.create());
		}
		else if(ranking == 4)
		{
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR_O.create());
		}
		else if(ranking == 4.5)
		{
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR_HALF_LEFT.create());
		}
		else if(ranking == 5)
		{
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR.create());
			this.add(VaadinIcon.STAR.create());
		}
		
		this.getChildren().forEach(c -> {
			((Icon)c).setSize("14px");
		});
	}
	
	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.setSizeUndefined();
	} // </generated-code>

}
