
package com.rapidclipse.vacationplanner.ui;

import java.time.format.DateTimeFormatter;

import com.rapidclipse.vacationplanner.HasTitle;
import com.rapidclipse.vacationplanner.entities.Vacation;
import com.rapidclipse.vacationplanner.microstream.MicroStream;
import com.vaadin.flow.component.html.Image;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;


@Route(value = "", layout = MainLayout.class)
public class HomeView extends VerticalLayout implements HasTitle
{
	public HomeView()
	{
		super();
		this.initUI();
		
		final Vacation v = MicroStream.root().getVacation();

		this.lblTitle.setText(v.getName());
		
		final DateTimeFormatter df = DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm");
		
		this.lblFrom.setText(v.getAppointments().get("Beginn").format(df));
		this.lblTo.setText(v.getAppointments().get("Ende").format(df));
		this.lblStart.setText(v.getAppointments().get("Abfahrt").format(df));
		this.lblReturn.setText(v.getAppointments().get("Rückkehr").format(df));
		this.lblShip.setText(v.getAppointments().get("Fähre").format(df));
	}

	@Override
	public String getTitle()
	{
		return "Home";
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.lblTitle          = new Label();
		this.image             = new Image();
		this.horizontalLayout  = new HorizontalLayout();
		this.label             = new Label();
		this.lblFrom           = new Label();
		this.horizontalLayout2 = new HorizontalLayout();
		this.label3            = new Label();
		this.lblTo             = new Label();
		this.horizontalLayout3 = new HorizontalLayout();
		this.label5            = new Label();
		this.lblStart          = new Label();
		this.horizontalLayout4 = new HorizontalLayout();
		this.label7            = new Label();
		this.lblReturn         = new Label();
		this.horizontalLayout5 = new HorizontalLayout();
		this.label9            = new Label();
		this.lblShip           = new Label();

		this.lblTitle.setText("Label");
		this.lblTitle.getStyle().set("font-weight", "bold");
		this.lblTitle.getStyle().set("font-size", "20px");
		this.image.setSrc("frontend/images/VomMeerTotal.jpg");
		this.horizontalLayout.getStyle().set("margin-top", "15px");
		this.label.setText("Bis:");
		this.label.getStyle().set("font-weight", "bold");
		this.lblFrom.setText("Label");
		this.lblFrom.getStyle().set("text-align", "right");
		this.label3.setText("Von:");
		this.label3.getStyle().set("font-weight", "bold");
		this.lblTo.setText("Label");
		this.lblTo.getStyle().set("text-align", "right");
		this.label5.setText("Abfahrt:");
		this.label5.getStyle().set("font-weight", "bold");
		this.lblStart.setText("Label");
		this.lblStart.getStyle().set("text-align", "right");
		this.label7.setText("Rückfahrt:");
		this.label7.getStyle().set("font-weight", "bold");
		this.lblReturn.setText("Label");
		this.lblReturn.getStyle().set("text-align", "right");
		this.label9.setText("Fähre:");
		this.label9.getStyle().set("font-weight", "bold");
		this.lblShip.setText("Label");
		this.lblShip.getStyle().set("text-align", "right");

		this.label.setSizeUndefined();
		this.lblFrom.setSizeUndefined();
		this.horizontalLayout.add(this.label, this.lblFrom);
		this.horizontalLayout.setFlexGrow(1.0, this.label);
		this.horizontalLayout.setFlexGrow(1.0, this.lblFrom);
		this.label3.setSizeUndefined();
		this.lblTo.setSizeUndefined();
		this.horizontalLayout2.add(this.label3, this.lblTo);
		this.horizontalLayout2.setFlexGrow(1.0, this.label3);
		this.horizontalLayout2.setFlexGrow(1.0, this.lblTo);
		this.label5.setSizeUndefined();
		this.lblStart.setSizeUndefined();
		this.horizontalLayout3.add(this.label5, this.lblStart);
		this.horizontalLayout3.setFlexGrow(1.0, this.label5);
		this.horizontalLayout3.setFlexGrow(1.0, this.lblStart);
		this.label7.setSizeUndefined();
		this.lblReturn.setSizeUndefined();
		this.horizontalLayout4.add(this.label7, this.lblReturn);
		this.horizontalLayout4.setFlexGrow(1.0, this.label7);
		this.horizontalLayout4.setFlexGrow(1.0, this.lblReturn);
		this.label9.setSizeUndefined();
		this.lblShip.setSizeUndefined();
		this.horizontalLayout5.add(this.label9, this.lblShip);
		this.horizontalLayout5.setFlexGrow(1.0, this.label9);
		this.horizontalLayout5.setFlexGrow(1.0, this.lblShip);
		this.lblTitle.setSizeUndefined();
		this.image.setWidth("250px");
		this.image.setHeight(null);
		this.horizontalLayout.setWidthFull();
		this.horizontalLayout.setHeight(null);
		this.horizontalLayout2.setWidthFull();
		this.horizontalLayout2.setHeight(null);
		this.horizontalLayout3.setWidthFull();
		this.horizontalLayout3.setHeight(null);
		this.horizontalLayout4.setWidthFull();
		this.horizontalLayout4.setHeight(null);
		this.horizontalLayout5.setWidthFull();
		this.horizontalLayout5.setHeight(null);
		this.add(this.lblTitle, this.image, this.horizontalLayout, this.horizontalLayout2, this.horizontalLayout3,
			this.horizontalLayout4, this.horizontalLayout5);
		this.setHorizontalComponentAlignment(FlexComponent.Alignment.CENTER, this.lblTitle);
		this.setHorizontalComponentAlignment(FlexComponent.Alignment.CENTER, this.image);
		this.setSizeFull();
	} // </generated-code>

	// <generated-code name="variables">
	private Image            image;
	private HorizontalLayout horizontalLayout, horizontalLayout2, horizontalLayout3, horizontalLayout4,
		horizontalLayout5;
	private Label            lblTitle, label, lblFrom, label3, lblTo, label5, lblStart, label7, lblReturn, label9,
		lblShip;
	// </generated-code>

}
