
package com.rapidclipse.vacationplanner.ui;

import com.rapidclipse.vacationplanner.HasTitle;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;


@Route(value = "package", layout = MainLayout.class)
public class PackingView extends VerticalLayout implements HasTitle
{
	public PackingView()
	{
		super();
		this.initUI();
	}
	
	@Override
	public String getTitle()
	{
		return "Package";
	}
	
	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.setSizeFull();
	} // </generated-code>
	
}
