
package com.rapidclipse.vacationplanner.ui;

import com.rapidclipse.vacationplanner.HasTitle;
import com.vaadin.flow.component.html.Paragraph;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;


@Route(value = "package", layout = MainLayout.class)
public class PackingView extends VerticalLayout implements HasTitle
{
	public PackingView()
	{
		super();
		this.initUI();
	}

	@Override
	public String getTitle()
	{
		return "Package";
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.paragraph = new Paragraph();

		this.paragraph.setText(
			"Here we have a list of all the tasks the user still has to do. It could also contain a nice little checkbox that plays a satisfying sound whenever a task is ticked off.");

		this.paragraph.setWidthFull();
		this.paragraph.setHeight(null);
		this.add(this.paragraph);
		this.setSizeFull();
	} // </generated-code>

	// <generated-code name="variables">
	private Paragraph paragraph;
	// </generated-code>

}
